FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the script into the container
COPY move_file.py .

# Run the script when the container launches
CMD ["python", "./move_file.py"]
